### ISSUE TITLE
Feature Request: Define custom rules and authentication

### ISSUE THREAD

**Issue by anonaut** [XanderStrike/lazy-legume#9]
Thanks very much for developing this awesome piece of code. is there any chance that you could add support for custom filters like "1080p and 720p", for groups like CtrlHD and formats like HDTV/WEB-DL and co? Also there is the question of security, because anybody that knows the port can steal the passkeys from your saved feeds. any plans to add authentication?

**Comment by XanderStrike** [comment]
I appreciate your kind words! I've added custom filters to the [top of the roadmap](https://trello.com/b/U7TrVYox/lazy-legume) and I'm just about to merge authentication.

Update with `git pull` then run `rake db:migrate db:seed`!
